In [14]:
import pandas as pd

road = pd.read_csv("../data/raw/Road_Accident_Data.csv")
events = pd.read_csv("../data/raw/World_Important_Dates.csv")

from IPython.display import display

print("Road Accident Data")
display(road.head())

print("World Important Dates")
display(events.head())

Road Accident Data

,Accident_Index,Accident Date,Day_of_Week,Junction_Control,Junction_Detail,Accident_Severity,Latitude,Light_Conditions,Local_Authority_(District),Carriageway_Hazards,...,Number_of_Casualties,Number_of_Vehicles,Police_Force,Road_Surface_Conditions,Road_Type,Speed_limit,Time,Urban_or_Rural_Area,Weather_Conditions,Vehicle_Type
0,200901BS70001,1/1/2021,Thursday,Give way or uncontrolled,T or staggered junction,Serious,51.512273,Daylight,Kensington and Chelsea,NaN,...,1,2,Metropolitan Police,Dry,One way street,30,15:11,Urban,Fine no high winds,Car
1,200901BS70002,1/5/2021,Monday,Give way or uncontrolled,Crossroads,Serious,51.514399,Daylight,Kensington and Chelsea,NaN,...,11,2,Metropolitan Police,Wet or damp,Single carriageway,30,10:59,Urban,Fine no high winds,Taxi/Private hire car
2,200901BS70003,1/4/2021,Sunday,Give way or uncontrolled,T or staggered junction,Slight,51.486668,Daylight,Kensington and Chelsea,NaN,...,1,2,Metropolitan Police,Dry,Single carriageway,30,14:19,Urban,Fine no high winds,Taxi/Private hire car
3,200901BS70004,1/5/2021,Monday,Auto traffic signal,T or staggered junction,Serious,51.507804,Daylight,Kensington and Chelsea,NaN,...,1,2,Metropolitan Police,Frost or ice,Single carriageway,30,8:10,Urban,Other,Motorcycle over 500cc
4,200901BS70005,1/6/2021,Tuesday,Auto traffic signal,Crossroads,Serious,51.482076,Darkness - lights lit,Kensington and Chelsea,NaN,...,1,2,Metropolitan Police,Dry,Single carriageway,30,17:25,Urban,Fine no high winds,Car

World Important Dates

,Sl. No,Name of Incident,Date,Month,Year,Country,Type of Event,Place Name,Impact,Affected Population,Important Person/Group Responsible,Outcome
0,1,Indus Valley Civilization Flourishes,Unknown,Unknown,2600 BC,India,Civilization,Indus Valley,Development of one of the world's earliest urb...,Local inhabitants,Indus Valley people,Positive
1,2,Battle of the Ten Kings,Unknown,Unknown,1400 BC,India,Battle,Punjab,Rigvedic tribes consolidated their control ove...,Rigvedic tribes,Sudas,Positive
2,6,Establishment of the Delhi Sultanate,Unknown,Unknown,1206,India,Political,Delhi,Muslim rule established in parts of India,People of Delhi and surrounding regions,QutbUnknownudUnknowndin Aibak,Mixed
3,7,Battle of Panipat,21,April,1526,India,Battle,Panipat,Foundation of the Mughal Empire in India,Northern Indian kingdoms,Babur,Mixed
4,8,Establishment of British Raj,1,May,1858,India,Colonial,Whole India,Start of direct British governance in India,Indian subcontinent,British East India Company/Empire,Negative

In [15]:
print("=== ROAD INFO ===")
print(road.info())

print("\n=== EVENTS INFO ===")
print(events.info())

print("\n=== NULL VALUES ROAD ===")
print(road.isnull().sum())

print("\n=== NULL VALUES EVENTS ===")
print(events.isnull().sum())

print("\n=== DUPLICATES ===")
print("Road:", road.duplicated().sum())
print("Events:", events.duplicated().sum())

=== ROAD INFO ===
<class 'pandas.DataFrame'>
RangeIndex: 307973 entries, 0 to 307972
Data columns (total 21 columns):
 #   Column                      Non-Null Count   Dtype
---  ------                      --------------   -----
 0   Accident_Index              307973 non-null  str
 1   Accident Date               307973 non-null  str
 2   Day_of_Week                 307973 non-null  str
 3   Junction_Control            307973 non-null  str
 4   Junction_Detail             307973 non-null  str
 5   Accident_Severity           307973 non-null  str
 6   Latitude                    307973 non-null  float64
 7   Light_Conditions            307973 non-null  str
 8   Local_Authority_(District)  307973 non-null  str
 9   Carriageway_Hazards         5424 non-null    str
 10  Longitude                   307973 non-null  float64
 11  Number_of_Casualties        307973 non-null  int64
 12  Number_of_Vehicles          307973 non-null  int64
 13  Police_Force                307973 non-null  str
 14  Road_Surface_Conditions     307656 non-null  str
 15  Road_Type                   306439 non-null  str
 16  Speed_limit                 307973 non-null  int64
 17  Time                        307956 non-null  str
 18  Urban_or_Rural_Area         307973 non-null  str
 19  Weather_Conditions          301916 non-null  str
 20  Vehicle_Type                307973 non-null  str
dtypes: float64(2), int64(3), str(16)
memory usage: 101.8 MB
None

=== EVENTS INFO ===
<class 'pandas.DataFrame'>
RangeIndex: 1096 entries, 0 to 1095
Data columns (total 12 columns):
 #   Column                              Non-Null Count  Dtype
---  ------                              --------------  -----
 0   Sl. No                              1096 non-null   int64
 1   Name of Incident                    1096 non-null   str
 2   Date                                1096 non-null   str
 3   Month                               1096 non-null   str
 4   Year                                1096 non-null   str
 5   Country                             1096 non-null   str
 6   Type of Event                       1096 non-null   str
 7   Place Name                          1096 non-null   str
 8   Impact                              1096 non-null   str
 9   Affected Population                 1096 non-null   str
 10  Important Person/Group Responsible  1096 non-null   str
 11  Outcome                             1096 non-null   str
dtypes: int64(1), str(11)
memory usage: 314.0 KB
None

=== NULL VALUES ROAD ===
Accident_Index                     0
Accident Date                      0
Day_of_Week                        0
Junction_Control                   0
Junction_Detail                    0
Accident_Severity                  0
Latitude                           0
Light_Conditions                   0
Local_Authority_(District)         0
Carriageway_Hazards           302549
Longitude                          0
Number_of_Casualties               0
Number_of_Vehicles                 0
Police_Force                       0
Road_Surface_Conditions          317
Road_Type                       1534
Speed_limit                        0
Time                              17
Urban_or_Rural_Area                0
Weather_Conditions              6057
Vehicle_Type                       0
dtype: int64

=== NULL VALUES EVENTS ===
Sl. No                                0
Name of Incident                      0
Date                                  0
Month                                 0
Year                                  0
Country                               0
Type of Event                         0
Place Name                            0
Impact                                0
Affected Population                   0
Important Person/Group Responsible    0
Outcome                               0
dtype: int64

=== DUPLICATES ===
Road: 1
Events: 0

In [16]:
import pandas as pd

road_parquet = pd.read_parquet("../data/processed/road_accident_data.parquet")
events_parquet = pd.read_parquet("../data/processed/world_important_dates.parquet")

In [17]:
from IPython.display import display

print("Road Accident Parquet")
display(road_parquet.head())

print("World Important Dates Parquet")
display(events_parquet.head())

Road Accident Parquet

,accident_index,accident_date,day_of_week,junction_control,junction_detail,accident_severity,latitude,light_conditions,local_authority_district,carriageway_hazards,...,number_of_casualties,number_of_vehicles,police_force,road_surface_conditions,road_type,speed_limit,time,urban_or_rural_area,weather_conditions,vehicle_type
0,200901bs70001,2021-01-01,thursday,give way or uncontrolled,t or staggered junction,serious,51.512273,daylight,kensington and chelsea,unknown,...,1,2,metropolitan police,dry,one way street,30,15:11,urban,fine no high winds,car
1,200901bs70002,2021-05-01,monday,give way or uncontrolled,crossroads,serious,51.514399,daylight,kensington and chelsea,unknown,...,11,2,metropolitan police,wet or damp,single carriageway,30,10:59,urban,fine no high winds,taxi/private hire car
2,200901bs70003,2021-04-01,sunday,give way or uncontrolled,t or staggered junction,slight,51.486668,daylight,kensington and chelsea,unknown,...,1,2,metropolitan police,dry,single carriageway,30,14:19,urban,fine no high winds,taxi/private hire car
3,200901bs70004,2021-05-01,monday,auto traffic signal,t or staggered junction,serious,51.507804,daylight,kensington and chelsea,unknown,...,1,2,metropolitan police,frost or ice,single carriageway,30,8:10,urban,other,motorcycle over 500cc
4,200901bs70005,2021-06-01,tuesday,auto traffic signal,crossroads,serious,51.482076,darkness - lights lit,kensington and chelsea,unknown,...,1,2,metropolitan police,dry,single carriageway,30,17:25,urban,fine no high winds,car

World Important Dates Parquet

,sl_no,name_of_incident,date,month,year,country,type_of_event,place_name,impact,affected_population,important_person_group_responsible,outcome
0,1,Indus Valley Civilization Flourishes,unknown,unknown,2600 BC,India,Civilization,Indus Valley,Development of one of the world's earliest urb...,Local inhabitants,Indus Valley people,Positive
1,2,Battle of the Ten Kings,unknown,unknown,1400 BC,India,Battle,Punjab,Rigvedic tribes consolidated their control ove...,Rigvedic tribes,Sudas,Positive
2,6,Establishment of the Delhi Sultanate,unknown,unknown,1206,India,Political,Delhi,Muslim rule established in parts of India,People of Delhi and surrounding regions,Qutbuddin Aibak,Mixed
3,7,Battle of Panipat,21,April,1526,India,Battle,Panipat,Foundation of the Mughal Empire in India,Northern Indian kingdoms,Babur,Mixed
4,8,Establishment of British Raj,1,May,1858,India,Colonial,Whole India,Start of direct British governance in India,Indian subcontinent,British East India Company/Empire,Negative

In [18]:
print("Road:", road_parquet.shape)
print("Events:", events_parquet.shape)

Road: (307972, 21)
Events: (1096, 12)